//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 04:55:09 PM CET 
//


package edu.yale.tp.cas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticationSuccessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthenticationSuccessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attributes" type="{http://www.yale.edu/tp/cas}AttributesType" minOccurs="0"/>
 *         &lt;element name="proxyGrantingTicket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="proxies" type="{http://www.yale.edu/tp/cas}ProxiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthenticationSuccessType", propOrder = {
    "user",
    "attributes",
    "proxyGrantingTicket",
    "proxies"
})
public class AuthenticationSuccessType {

    @XmlElement(required = true)
    protected String user;
    protected AttributesType attributes;
    protected String proxyGrantingTicket;
    protected ProxiesType proxies;

    /**
     * Default no-arg constructor
     * 
     */
    public AuthenticationSuccessType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AuthenticationSuccessType(final String user, final AttributesType attributes, final String proxyGrantingTicket, final ProxiesType proxies) {
        this.user = user;
        this.attributes = attributes;
        this.proxyGrantingTicket = proxyGrantingTicket;
        this.proxies = proxies;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the proxyGrantingTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyGrantingTicket() {
        return proxyGrantingTicket;
    }

    /**
     * Sets the value of the proxyGrantingTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyGrantingTicket(String value) {
        this.proxyGrantingTicket = value;
    }

    /**
     * Gets the value of the proxies property.
     * 
     * @return
     *     possible object is
     *     {@link ProxiesType }
     *     
     */
    public ProxiesType getProxies() {
        return proxies;
    }

    /**
     * Sets the value of the proxies property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxiesType }
     *     
     */
    public void setProxies(ProxiesType value) {
        this.proxies = value;
    }

}
