//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 04:55:09 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.yale.edu/tp/cas", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns={@javax.xml.bind.annotation.XmlNs(prefix="cas", namespaceURI="http://www.yale.edu/tp/cas")})
package edu.yale.tp.cas;
